// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp5iSeIeVqoeqPDgkbfs0vyxxbV1dBXgY',
    appId: '1:745466454052:web:068792a12d227f6765f8b1',
    messagingSenderId: '745466454052',
    projectId: 'prjpab2-si6d-2226240114',
    authDomain: 'prjpab2-si6d-2226240114.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6d-2226240114-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-2226240114.firebasestorage.app',
    measurementId: 'G-0K0YEFJHCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_SpNCBzNr2J_y9qo_c1pCUCSu_wMzHg0',
    appId: '1:745466454052:android:3614304553f9509b65f8b1',
    messagingSenderId: '745466454052',
    projectId: 'prjpab2-si6d-2226240114',
    databaseURL: 'https://prjpab2-si6d-2226240114-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-2226240114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsBaSkRjvUqyEm_ONx3VC_BcJoJTQS4eM',
    appId: '1:745466454052:ios:b911162a6504a58065f8b1',
    messagingSenderId: '745466454052',
    projectId: 'prjpab2-si6d-2226240114',
    databaseURL: 'https://prjpab2-si6d-2226240114-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-2226240114.firebasestorage.app',
    iosClientId: '745466454052-3tt9kohf1ua4l2f9l3i2na5b76lres69.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsBaSkRjvUqyEm_ONx3VC_BcJoJTQS4eM',
    appId: '1:745466454052:ios:b911162a6504a58065f8b1',
    messagingSenderId: '745466454052',
    projectId: 'prjpab2-si6d-2226240114',
    databaseURL: 'https://prjpab2-si6d-2226240114-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-2226240114.firebasestorage.app',
    iosClientId: '745466454052-3tt9kohf1ua4l2f9l3i2na5b76lres69.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp5iSeIeVqoeqPDgkbfs0vyxxbV1dBXgY',
    appId: '1:745466454052:web:068792a12d227f6765f8b1',
    messagingSenderId: '745466454052',
    projectId: 'prjpab2-si6d-2226240114',
    authDomain: 'prjpab2-si6d-2226240114.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6d-2226240114-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-2226240114.firebasestorage.app',
    measurementId: 'G-0K0YEFJHCQ',
  );

  

}